name: geog0111
channels: 
    - conda-forge
dependencies:
    - numpy
    - beautifulsoup4
    - lxml
    - cryptography
    - python>=3.6
    - ipython
    - numpy 
    - scipy
    - matplotlib 
    - gdal>2.2
    - pandas  
    - requests
